#+TITLE: Getting Started with Scala 3
#+STARTUP: entitiespretty
#+STARTUP: indent
#+STARTUP: overview

* DONE Try Scala without installing anything
  CLOSED: [2021-06-11 Fri 01:30]
  [[https://scastie.scala-lang.org/?target=dotty][Scastie]]

* DONE Install Scala on your computer
  CLOSED: [2021-06-11 Fri 01:59]
** Using the Scala Installer (recommended way)
   =TODO= Learn more about using _Coursier_ =TODO=
   =TODO= Learn more about using _Coursier_ =TODO=
   =TODO= Learn more about using _Coursier_ =TODO=
   =TODO= Learn more about using _Coursier_ =TODO=
   =TODO= Learn more about using _Coursier_ =TODO=

   Install with _Coursier_.

   - Use ~cs setup~ to checks if your system has a JVM and the standard Scala
     applications, and installs them if needed.

** ... or manually
   - Only two tools are required for compiling, running, testing, and packaging a
     Scala project:
     * JDK 8 or JDK 11
     * sbt

   - To install JDK and sbt manually:
     1. Download _JDK 8_ or _JDK 11_.
        * Refer to [[https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html][Java Compatibility]] for Scala/Java compatibility detail.

     2. Install _sbt_.

* DONE Create a “Hello, world” project with sbt
  CLOSED: [2021-06-11 Fri 02:18]
  To create a project, you can EITHER use a _command-line tool_ OR an _IDE_.
  * If you are familiar with the _command line_, we recommend that approach.

** Using the command line
   - sbt is a build tool for Scala.
     sbt _compiles_, _runs_, and _tests_ your Scala code.
     (It can also _publish_ libraries and do many other tasks.)

   - ~sbt new scala/scala3.g8~
     This pulls the ='hello-world' template= from GitHub.

* DONE Open the “Hello, world” project
  CLOSED: [2021-06-11 Fri 15:59]
** DONE Using IntelliJ IDEA
   CLOSED: [2021-06-11 Fri 15:54]
   Open the =build.sbt= file, then choose "Open as a project".
   - =from Jian=
     Don't open the whole project folder. When you do this, the first several auto
     builds may fail, and you need to use sbt command line or sbt to manually type
     commands and build.
       Open the ="build.sbt"= rather than the folder can resolve this issue. I
     didn't know this until I read this document. I guess this should be in the
     Scala IntelliJ plugin document, but I never read.

** DONE Using VS Code with Metals
   CLOSED: [2021-06-11 Fri 15:59]
   Remeber to install the /Metals/ extension.
     Then you can use VS Code to open the directory containing your =build.sbt=.
   When prompted to do so, select "Import build".
   =from Jian=
   Currently, when the "Import build" is done, and you open a source file, the
   Scala 3 may not be identified. I see this issue. However, after several seconds,
   the /Metals/ automatically start working again, still some "import" work, and
   then finally the Scala 3 code can be identified.
   =WHAT is the exact REASON?=

** DONE View the source code
   CLOSED: [2021-06-11 Fri 15:59]

* DONE Run the “Hello, world” project
  CLOSED: [2021-06-11 Fri 16:02]
  Use IDE or use sbt.

  - During your development, the ~ prefixed sbt commands can help you to re-run
    on every file save.

  - Press ~[Enter]~ to *interrupt* the ~run~ command.

  - Type ~exit~ or press ~[Ctrl][d]~ to quit the sbt console.

* DONE Next steps
  CLOSED: [2021-06-11 Fri 16:02]
