#+TITLE: Ciris
#+SUBTITLE: Functional Configurations for Scala
#+VERSION: 1.2.1
#+STARTUP: overview
#+STARTUP: entitiespretty

* Overview
** Getting Started
   To get started with sbt, add the following line to your =build.sbt= file.
   #+begin_src scala
     libraryDependencies += "is.cir" %% "ciris" % "1.2.1"
   #+end_src

   - Published for Scala 2.12 and 2.13. For changes, refer to the release notes.

   - For Scala 2.12, enable /partial unification/ by adding the following line to
     =build.sbt=.
     #+begin_src scala
       scalacOptions += "-Ypartial-unification"
     #+end_src

*** Modules
    Following are additional provided modules.

**** Circe
     #+begin_src scala
       libraryDependencies += "is.cir" %% "ciris-circe" % "1.2.1"
     #+end_src
     
**** Enumeratum
     #+begin_src scala
       libraryDependencies += "is.cir" %% "ciris-enumeratum" % "1.2.1"
     #+end_src
     
**** Refined
     #+begin_src scala
       libraryDependencies += "is.cir" %% "ciris-refined" % "1.2.1"
     #+end_src
     
**** Squants
     #+begin_src scala
       libraryDependencies += "is.cir" %% "ciris-squants" % "1.2.1"
     #+end_src
     
**** External Modules
     Following is an incomplete list of third-party integrations.
     - ciris-aiven-kafka
     - ciris-aws-secretsmanager
     - ciris-aws-ssm
     - ciris-credstash
     - ciris-hocon
     - ciris-kubernetes
     
*** Signatures
*** Compatibility
*** Snapshot Release
    #+begin_src scala
      resolvers += Resolver.sonatypeRepo("snapshots")

      libraryDependencies += "is.cir" %% "ciris" % "1.2.1+60-e94f5c87-SNAPSHOT"
    #+end_src
    
** Dependencies
   | Module           | Dependencies      | Scala      |
   |------------------+-------------------+------------|
   | ciris            | Cats Effect 2.2.0 | 2.12, 2.13 |
   | ciris-circe      | Circe 0.13.0      | 2.12, 2.13 |
   | ciris-enumeratum | Enumeratum 1.6.1  | 2.12, 2.13 |
   | ciris-refined    | Refined 0.9.18    | 2.12, 2.13 |
   | ciris-squants    | Squants 1.7.0     | 2.12, 2.13 |
   
** Participation
   Ciris embraces *pure*, *typeful*, *idiomatic functional programming* in Scala,
   and wants to provide a _safe and friendly environment_ for teaching, learning,
   and contributing as described in the Scala Code of Conduct.
   
** License
   MIT license

* Quick Example
* Configurations
** Defaults
** Secrets
*** Redacting
    
** Loading
** Decoders
** Sources
    
* Modules
  The following sections describe the additional modules.
  
** Circe
** Enumeratum
** Refined
** Squants
