#+TITLE: The Book of R
#+SUBTITLE: A First Course in Programming and Statistics
#+VERSION: 2016
#+AUTHOR: Tilman M. Davies
#+STARTUP: entitiespretty
#+STARTUP: indent
#+STARTUP: overview

* PREFACE - xxiii
* ACKNOWLEDGMENTS - xxv
* INTRODUCTION - xxvii
** A Brief History of R - xxvii
** About This Book - xxviii
*** Part I: The Language - xxviii
*** Part II: Programming - xxix
*** Part III: Statistics and Probability - xxix
*** Part IV: Statistical Testing and Modeling - xxix
*** Part V: Advanced Graphics - xxx

** For Students - xxx
** For Instructors - xxxi

* PART I THE LANGUAGE
** 1 GETTING STARTED - 3
*** 1.1 Obtaining and Installing R from CRAN - 3
*** 1.2 Opening R for the First Time - 4
**** 1.2.1 Console and Editor Panes - 5
**** 1.2.2 Comments - 6
**** 1.2.3 Working Directory - 7
**** 1.2.4 Installing and Loading R Packages - 7
**** 1.2.5 Help Files and Function Documentation - 8
**** 1.2.6 Third-Party Editors - 11

*** 1.3 Saving Work and Exiting R - 11
**** 1.3.1 Workspaces. - 11
**** 1.3.2 Scripts - 12

*** 1.4 Conventions - 12
**** 1.4.1 Coding - 13
**** 1.4.2 Math and Equation References - 14
**** 1.4.3 Exercises - 14

*** Exercise 1.1 - 14

** 2 NUMERICS, ARITHMETIC, ASSIGNMENT, AND VECTORS - 17
*** 2.1 R for Basic Math - 17
**** 2.1.1 Arithmetic - 18
**** 2.1.2 Logarithms and Exponentials - 19
**** 2.1.3 E-Notation - 20
**** Exercise 2.1 - 21

*** 2.2 Assigning Objects - 21
**** Exercise 2.2 - 22

*** 2.3 Vectors - 23
**** 2.3.1 Creating a Vector - 23
**** 2.3.2 Sequences, Repetition, Sorting, and Lengths - 24
**** Exercise 2.3 - 27
**** 2.3.3 Subsetting and Element Extraction - 28
**** Exercise 2.4 - 32
**** 2.3.4 Vector-Oriented Behavior - 33
**** Exercise 2.5 - 36

** 3 MATRICES AND ARRAYS - 39
*** 3.1 Defining a Matrix - 39
**** 3.1.1 Filling Direction - 40
**** 3.1.2 Row and Column Bindings - 41
**** 3.1.3 Matrix Dimensions - 42

*** 3.2 Subsetting - 42
**** 3.2.1 Row, Column, and Diagonal Extractions - 43
**** 3.2.2 Omitting and Overwriting - 44
**** Exercise 3.1 - 47

*** 3.3 Matrix Operations and Algebra - 47
**** 3.3.1 Matrix Transpose - 47
**** 3.3.2 Identity Matrix - 48
**** 3.3.3 Scalar Multiple of a Matrix - 49
**** 3.3.4 Matrix Addition and Subtraction - 49
**** 3.3.5 Matrix Multiplication - 50
**** 3.3.6 Matrix Inversion - 51
**** Exercise 3.2 - 52

*** 3.4 Multidimensional Arrays - 52
**** 3.4.1 Definition - 53
**** 3.4.2 Subsets, Extractions, and Replacements - 55
**** Exercise 3.3 - 58

** 4 NON-NUMERIC VALUES - 59
*** 4.1 Logical Values - 59
**** 4.1.1 TRUE or FALSE? - 60
**** 4.1.2 A Logical Outcome: Relational Operators - 60
**** Exercise 4.1 - 64
**** 4.1.3 Multiple Comparisons: Logical Operators - 64
**** Exercise 4.2 - 67
**** 4.1.4 Logicals Are Numbers! - 67
**** 4.1.5 Logical Subsetting and Extraction - 68
**** Exercise 4.3 - 72

*** 4.2 Characters - 72
**** 4.2.1 Creating a String - 73
**** 4.2.2 Concatenation - 74
**** 4.2.3 Escape Sequences - 76
**** 4.2.4 Substrings and Matching - 77
**** Exercise 4.4 - 78

*** 4.3 Factors - 79
**** 4.3.1 Identifying Categories - 79
**** 4.3.2 Defining and Ordering Levels - 82
**** 4.3.3 Combining and Cutting. - 83
**** Exercise 4.5 - 86

** 5 LISTS AND DATA FRAMES - 89
*** 5.1 Lists of Objects - 89
**** 5.1.1 Definition and Component Access - 89
**** 5.1.2 Naming - 91
**** 5.1.3 Nesting - 93
**** Exercise 5.1 - 94

*** 5.2 Data Frames - 95
**** 5.2.1 Construction - 96
**** 5.2.2 Adding Data Columns and Combining Data Frames - 98
**** 5.2.3 Logical Record Subsets - 100
**** Exercise 5.2 - 101

** 6 SPECIAL VALUES, CLASSES, AND COERCION - 103
*** 6.1 Some Special Values - 103
**** 6.1.1 Infinity - 104
**** 6.1.2 NaN - 106
**** Exercise 6.1 - 107
**** 6.1.3 NA - 108
**** 6.1.4 NULL - 110
**** Exercise 6.2 - 113

*** 6.2 Understanding Types, Classes, and Coercion - 114
**** 6.2.1 Attributes - 114
**** 6.2.2 Object Class - 116
**** 6.2.3 Is-Dot Object-Checking Functions - 119
**** 6.2.4 As-Dot Coercion Functions - 120
**** Exercise 6.3 - 125

** 7 BASIC PLOTTING - 127
*** 7.1 Using plot with Coordinate Vectors - 127
*** 7.2 Graphical Parameters - 129
**** 7.2.1 Automatic Plot Types - 129
**** 7.2.2 Title and Axis Labels - 130
**** 7.2.3 Color - 131
**** 7.2.4 Line and Point Appearances - 133
**** 7.2.5 Plotting Region Limits - 133

*** 7.3 Adding Points, Lines, and Text to an Existing Plot - 134
**** Exercise 7.1 - 139

*** 7.4 The ggplot2 Package - 139
**** 7.4.1 A Quick Plot with qplot - 140
**** 7.4.2 Setting Appearance Constants with Geoms - 141
**** 7.4.3 Aesthetic Mapping with Geoms - 143
**** Exercise 7.2 - 146

** 8 READING AND WRITING FILES - 147
*** 8.1 R-Ready Data Sets - 147
**** 8.1.1 Built-in Data Sets - 148
**** 8.1.2 Contributed Data Sets - 149

*** 8.2 Reading in External Data Files - 150
**** 8.2.1 The Table Format - 150
**** 8.2.2 Spreadsheet Workbooks - 153
**** 8.2.3 Web-Based Files - 154
**** 8.2.4 Other File Formats - 155

*** 8.3 Writing Out Data Files and Plots - 156
**** 8.3.1 Data Sets - 156
**** 8.3.2 Plots and Graphics Files - 157

*** 8.4 Ad Hoc Object Read/Write Operations - 160
**** Exercise 8.1 - 161

* PART II PROGRAMMING
** 9 CALLING FUNCTIONS 165
*** 9.1 Scoping . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 165
*** 9.1.1 Environments . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 166
*** 9.1.2 Search Path . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 168
*** 9.1.3 Reserved and Protected Names . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 170
*** Exercise 9.1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 172
*** 9.2 Argument Matching. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 172
*** 9.2.1 Exact . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 172
*** 9.2.2 Partial . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 173
*** 9.2.3 Positional . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 174
*** 9.2.4 Mixed . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 175
*** 9.2.5 Dot-Dot-Dot: Use of Ellipses . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 176
*** Exercise 9.2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 177
*** 10
*** CONDITIONS AND LOOPS 179
*** 10.1 if Statements . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 179
*** 10.1.1 Stand-Alone Statement . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 180
*** 10.1.2 else Statements . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 183
*** 10.1.3 Using ifelse for Element-wise Checks . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 184
*** Exercise 10.1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 185
*** 10.1.4 Nesting and Stacking Statements . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 186
*** 10.1.5 The switch Function . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 189
*** Exercise 10.2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 191
*** 10.2 Coding Loops . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 193
*** 10.2.1 for Loops . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 193
*** Exercise 10.3 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 199
*** 10.2.2 while Loops . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 200
*** Exercise 10.4 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 203
*** 10.2.3 Implicit Looping with apply . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 204
*** Exercise 10.5 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 208
*** 10.3 Other Control Flow Mechanisms . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 209
*** 10.3.1 Declaring break or next . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 209
*** 10.3.2 The repeat Statement . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 211
*** Exercise 10.6 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 213
*** 11
*** WRITING FUNCTIONS 215
*** 11.1 The function Command. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 215
*** 11.1.1 Function Creation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 216
*** 11.1.2 Using return . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 220
*** Exercise 11.1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 221
*** 11.2 Arguments . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 222
*** 11.2.1 Lazy Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 222
*** 11.2.2 Setting Defaults . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 225
*** 11.2.3 Checking for Missing Arguments . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 227
*** 11.2.4 Dealing with Ellipses . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 228
*** Exercise 11.2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 231
*** 11.3 Specialized Functions . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 233
*** 11.3.1 Helper Functions . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 233
*** 11.3.2 Disposable Functions . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 236
*** 11.3.3 Recursive Functions . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 237
*** Exercise 11.3 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 238
*** 12
*** EXCEPTIONS, TIMINGS, AND VISIBILITY 241
*** 12.1 Exception Handling . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 241
*** 12.1.1 Formal Notifications: Errors and Warnings . . . . . . . . . . . . . . . . . . . . . . . . 242
*** 12.1.2 Catching Errors with try Statements . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 244
*** Exercise 12.1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 247
*** 12.2 Progress and Timing . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 249
*** 12.2.1 Textual Progress Bars: Are We There Yet? . . . . . . . . . . . . . . . . . . . . . . . . . 249
*** 12.2.2 Measuring Completion Time: How Long Did It Take? . . . . . . . . . . . . . . . 250
*** Exercise 12.2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 251
*** 12.3 Masking . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 252
*** 12.3.1 Function and Object Distinction . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 252
*** 12.3.2 Data Frame Variable Distinction . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 255
*** PART III
*** STATISTICS AND PROBABILITY
*** 13
*** ELEMENTARY STATISTICS 261
*** 13.1 Describing Raw Data . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 261
*** 13.1.1 Numeric Variables . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 262
*** 13.1.2 Categorical Variables . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 262
*** 13.1.3 Univariate and Multivariate Data . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 264
*** 13.1.4 Parameter or Statistic? . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 265
*** Exercise 13.1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 266
*** 13.2 Summary Statistics . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 267
*** 13.2.1 Centrality: Mean, Median, Mode . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 267
*** 13.2.2 Counts, Percentages, and Proportions . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 271
*** Exercise 13.2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 273
*** 13.2.3 Quantiles, Percentiles, and the Five-Number Summary . . . . . . . . . . . . . . 274
*** 13.2.4 Spread: Variance, Standard Deviation, and the Interquartile Range. . 275
*** Exercise 13.3 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 279
*** 13.2.5 Covariance and Correlation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 280
*** 13.2.6 Outliers . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 285
*** Exercise 13.4 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 287
*** 14
*** BASIC DATA VISUALIZATION 289
*** 14.1 Barplots and Pie Charts . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 289
*** 14.1.1 Building a Barplot . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 289
*** 14.1.2 A Quick Pie Chart . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 293
*** 14.2 Histograms . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 294
*** 14.3 Box-and-Whisker Plots . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 298
*** 14.3.1 Stand-Alone Boxplots . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 298
*** 14.3.2 Side-by-Side Boxplots . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 299
*** 14.4 Scatterplots . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 300
*** 14.4.1 Single Plot . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 301
*** 14.4.2 Matrix of Plots . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 302
*** Exercise 14.1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 306
*** 15
*** PROBABILITY 309
*** 15.1 What Is a Probability? . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 309
*** 15.1.1 Events and Probability . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 310
*** 15.1.2 Conditional Probability . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 311
*** 15.1.3 Intersection . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 311
*** 15.1.4 Union. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 312
*** 15.1.5 Complement . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 312
*** Exercise 15.1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 313
*** 15.2 Random Variables and Probability Distributions. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 314
*** 15.2.1 Realizations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 314
*** 15.2.2 Discrete Random Variables . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 315
*** 15.2.3 Continuous Random Variables . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 318
*** 15.2.4 Shape, Skew, and Modality . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 326
*** Exercise 15.2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 327
*** 16
*** COMMON PROBABILITY DISTRIBUTIONS 331
*** 16.1 Common Probability Mass Functions. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 332
*** 16.1.1 Bernoulli Distribution . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 332
*** 16.1.2 Binomial Distribution . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 333
*** Exercise 16.1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 338
*** 16.1.3 Poisson Distribution . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 338
*** Exercise 16.2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 341
*** 16.1.4 Other Mass Functions . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 342
*** 16.2 Common Probability Density Functions . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 342
*** 16.2.1 Uniform . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 343
*** Exercise 16.3 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 347
*** 16.2.2 Normal . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 348
*** Exercise 16.4 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 356
*** 16.2.3 Student’s t-distribution . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 357
*** 16.2.4 Exponential . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 359
*** Exercise 16.5 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 362
*** 16.2.5 Other Density Functions . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 362
