#+TITLE: A Little Smalltalk!
#+VERSION: 1987
#+AUTHOR: Timothy Budd
#+STARTUP: overview
#+STARTUP: entitiespretty

* PART ONE. The Language - 1
** CHAPTER 1  Basics 3
*** Objects, Classes, and Inheritance 5
*** History, Background Reading 9
    This chapter introduces the basic concepts of the Smalltalk language; namely
    object, method, class, inheritance and overriding.

** CHAPTER 2  Syntax 12
*** Literal Constants 13
*** Identifiers 14
*** Messages 15
*** Getting Started 17
*** Finding Out About Objects 18
*** Blocks 19
*** Comments and Continuations 20
    This chapter introduces the syntax for literal objects (such as numbers)
    and the syntax for messages. It explains how to use the Little Smalltalk
    system to evaluate expressions typed in directly at the keyboard and
    how to use a few simple messages to discover information about different
    types of objects.

** CHAPTER 3  Basic Classes 22
*** Basic Objects 23
*** Collections 24
*** Control Structures 28
*** Class Management 30
*** Abstract Superclasses 32
    The basic classes included in the Little Smalltalk standard library are
    explained in this chapter.

** CHAPTER 4  Class Definition 34
*** An Illustrative .Example 37
*** Processing a Class Definition 39
    This chapter introduces the syntax used for defining classes. An example
    class definition is presented.

** CHAPTER 5  A Simple Application 42
*** Saving Environments 49
    This chapter illustrates the development of a simple application in
    Smalltalk and describes how environments can be saved and restored.

** CHAPTER 6  Primitives, Cascades, and Coercions 51
*** Cascades 52
*** Primitives 53
*** Numbers 54
    This chapter introduces the syntax for cascaded expressions and describes
    the notion of primitive expressions. It illustrates the use of primitives by
    showing how primitives are used to produce the correct results for mixed
    mode arithmetic operations.

** CHAPTER 7  A Simulation 59
*** The Ice Cream Store Simulation 60
*** Further Reading 72
    This chapter presents a simple simulation of an ice cream store,
    illustrating the ease with which simulations can be described in Smalltalk.

** CHAPTER 8  Generators 74
*** Filters 79
*** Goal-Directed Evaluation 81
*** Operatkms on Generators 84
*** Further Reading 91
    This chapter introduces the concept of generators and shows how generators
    can be used in the solution of problems requiring goaldirected evaluation.

** CHAPTER 9  Graphics 95
*** Character Graphics 97
*** Line Graphics 102
*** Bit-Mapped Graphics 106
    Although graphics are not fundamental to Little Smalltalk in the same way
    that they are an intrinsic part of the Smalltalk-80 system, it is still
    possible to describe some graphics functions using the language. This
    chapter details three types of approaches to graphics.

** CHAPTER 10 Processes 109
*** Semaphores 114
*** Monitors 115
*** The Dining Philosophers Problem 116
*** Further Reading 122
    This chapter introduces the concepts of processes and semaphores. It
    illustrates these concepts using the dining philosophers problem.

* PART TWO. The Implementation - 125
** CHAPTER 11. Implementation Overview - 127
*** Identifier Typelessness - 129
*** Unscoped Lifetimes - 129
*** An Interactive System - 131
*** A Multi-Processing Language - 132
*** System Overview - 135
    This chapter describes the features that make an interpreter for the
    Smalltalk language different from, say, a Pascal compiler. Provides a
    high-level description of the major components in the Little Smalltalk
    system.

** CHAPTER 12. The Representation ofObjects - 137
*** Special Objects - 141
*** Memory Management - 144
*** Optimizations - 148
    The internal representation of objects in the Little Smalltalk system is
    described in this chapter, which also overviews the memory management
    algorithms. The chapter ends with a discussion of several optimizations used
    to improve the speed of the Little Smalltalk system.

** CHAPTER 13. Bytecodes - 150
*** The Representation of Methods - 156
*** Optimizations - 157
*** Dynamic Optimizations - 159
    The techniques used to represent methods internally in the Little Smalltalk
    system are described in this chapter.

** CHAPTER 14. The Process Manager - 161
*** The Driver - 170
*** The Class Parser - 172
    This chapter presents a more detailed view of the central component of the
    Little Smalltalk system, the process manager. It then goes on to describe
    the driver, the process that reads commands from the user terminal and
    schedules them for execution. The chapter ends by describing the class
    parser and the internal representation of classes.

** CHAPTER 15. The Interpreter - 176
*** Push Opcodes - 179
*** Pop Opcodes - 182
*** Message-Sending Opcodes - 182
*** Block Creation - 185
*** Special Instructions - 186
*** The Courier - 189
*** The Primitive Handler - 189
*** Blocks - 190
 This chapter describes the actions of the interpreter and the courier
 in executing bytecodes and passing messages. It ends by describing
 the primitive handler and the manipulation of special objects.
 
* References - 193
  An annotated bibliography of references related to the Little Smalltalk system.

* Projects - 198
* Appendices - 209
** APPENDIX 1. Running Little Smalltalk - 209
   Describes how to run the Little Smalltalk system. Lists the various options
   available.

** APPENDIX 2. Syntax Charts - 213
   Presents syntax charts describing the language accepted by the Little
   Smalltalk system.

** APPENDIX 3. Class Descriptions - 225
   Presents descriptions of the various messages to which the classes in the
   standard library will respond.

** APPENDIX 4. Primitives - 261
   Gives the meanings of the various primitive numbers.

** APPENDIX 5. Differences Between Little Smalltalk and the Smalltalk-80 Programming System - 272
   Describes the differences between Little Smalltalk and the Xerox Smalltalk-80
   systems.
