#+TITLE: Apache Ant\trade{} 1.10.8 Manual
#+STARTUP: overview
#+STARTUP: entitiespretty

* Introduction
  - =EN= wrinkles

** Why?
   - =EN= dreaded

   - =TODO=

   - Ant is different.

     Instead of a model where it is extended with shell-based commands (the other
     building toos do this),

     Ant is extended using Java classes.
     Instead of writing shell commands, the configuration files are XML-based,
     calling out a target tree where various tasks get executed. =TODO=
     Each task is run by an object that implements a particular Task interface.
     =TODO=

   - Ant is cross-platform

   - Ant has an ~<exec>~ task that allows different commands to be executed based
     on the OS it is executing on.

** 
* Installing Apache Ant
* Using Apache Ant
* Running Apache Ant
* Ant Tasks
* Concepts and Types
* Loggers & Listeners
* Editor/IDE Integration
* Developing with Ant
* Tutorials
* Ant API
* License
* Feedback and Troubleshooting
* Authors
