#+TITLE: Giter8
#+VERSION: 0.14.0
#+STARTUP: entitiespretty
#+STARTUP: indent
#+STARTUP: overview

*Giter8* is a _command line tool_ to generate files and directories from
templates published on GitHub or any other git repository.

- It's implemented in _Scala_ and runs through the _sbt launcher_ (=TODO=),
  *BUT* it can produce output *for ANY purpose*.

*** sbt new integration
    From sbt 0.13.13 on, Giter8 can be called from sbt's ~new~ command as follows:
    #+begin_src shell
      sbt new scala/scala-seed.g8
    #+end_src

*** Credits
    - Original implementation (C) 2010-2015 _Nathan Hamblen_ and _contributors_
    - Adapted and extended in 2016 by _foundweekends project_

    Giter8 is licensed under *Apache 2.0 license*

* 1. Setup
*** Coursier
    _Giter8_, and other Scala command line tools, can be installed using *Coursier*.

    - See the _coursier installation instruction_ (=TODO=) to add it to your path.

    - Installation:
      #+begin_src shell
        cs install giter8
      #+end_src

      * Update:
        #+begin_src shell
          cs update g8
        #+end_src

*** Manual
    Download from Maven Central and install giter8:
    #+begin_src shell
      curl https://repo1.maven.org/maven2/org/foundweekends/giter8/giter8-bootstrap_2.12/0.13.1/giter8-bootstrap_2.12-0.13.1.sh > ~/bin/g8
      chmod +x ~/bin/g8
    #+end_src
    Make sure this _g8_ executable is in the location that is part of your ~$PATH~.

    - After installation, try running ~g8~ with no parameters, and you should see:
      #+begin_src shell
        # Error: Missing argument <template>
        # Try --help for more information.
      #+end_src

* 2. Usage
  - _Template repositories_ can reside on GitHub

  - _Template repositories_ should be named with the _suffix *.g8*._

  - We're keeping a [[https://github.com/foundweekends/giter8/wiki/giter8-templates][list of templates on the wiki]].

  - Examples of applying a template:
    #+begin_src shell
      # Equivalent
      g8 unfiltered/unfilteredd.g8
      g8 https://github.com/unfiltered/unfilteredd.g8

      # Local template
      g8 file://path/to/template
    #+end_src
    * After running the above commands, you'll be *promptedd* for EACH _parameter_,
      with _its *default value* in square brackets_ in the form like =name [My Web Project]:=.

  - Check the output of ~g8 --help~ to learn more details.
    * You can fetch a specific branch, tag, or even a specific directory (=TODO= DIRECTORY???).

    * You can specify these parameters in command line. Please check the
      output of ~g8 --help~.




*** Private Repositories
    Giter8 will use your _ssh key_ to access private repositories, just LIKE *git* does.

*** SSH Agent - =TODO= =READ when REQUIRED=

* 3. Making your own templates
*** Use CC0 1.0 for template licensing
    - We RECOMMEND licensing software templates under *CC0 1.0*,
      which _WAIVES all copyrights and related rights_, SIMILAR TO the "public domain."

    - =DETAILS=

*** template layout
    The g8 runtime looks for templates in *TWO locations* in a given GitHub project:
    - If the =src/main/g8= directory is present, it is used (=src= layout).
    - If it does *NOT exist*, then the _root directory_ is used (=root= layout)

*** src layout
*** default.properties
*** Template comments
*** Conditionals
*** name field
*** package field
*** verbatim field
*** Maven properties
*** root layout

** a. Formatting template fields
** b. Testing templates locally
*** Using the Giter8Plugin

* 4. Scaffolding plugin
*** Using the scaffold plugin
    - Giter8 supplies an _sbt plugin_ for
      _TESTING templates
      BEFORE pushing them to a GitHub branch._

      * If you used the =foundweekends/giter8.g8= template recommended above,
        it should already be configured.

    - *Upgrade* an EXISTING template project to the CURRENT plugin,
      you can add this as a source dependency in =project/giter8.sbt=:
      #+begin_src scala
        addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8" % "0.12.0")
      #+end_src

*** Creating a scaffold

* 5. Contributing
* 5. Contributing
*** Installing local version of giter8
**** Fixing PATH
**** To install local version
**** To refresh
**** To get back to normal version
